# Generated by Django 2.1.5 on 2019-04-22 03:57

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190419_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='PublicOrPrivate'),
        ),
        migrations.AddField(
            model_name='post',
            name='outline',
            field=models.TextField(blank=True, verbose_name='Outline'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownx.models.MarkdownxField(help_text='Writing in Markdown', verbose_name='PostContent'),
        ),
    ]
